#!/usr/bin/env bash
set -e

test -d .venv || pushd ..
. .venv/bin/activate

# ICMP client A
python -m mt --taddr ${local_tun:-10.20.0.1} icmp --lif ${local_if:-enp0s8} --addr ${remote:-192.168.56.106}
