#!/usr/bin/env bash
set -e

test -d .venv || pushd ..
. .venv/bin/activate

# ICMP client B
python -m mt --taddr ${local_tun:-10.20.0.2} icmp --lif ${local_if:-enp0s8} --addr ${remote:-192.168.56.105}
